import type { WordEntry } from '../../../types/phonetics'

/**
 * Placeholder word list for the Phase 1 prototype only — NOT the final
 * Lexique383-derived lexicon (see the project plan, Phase 2). Phoneme
 * sequences use the real 34-tile ID space from `src/data/phonemes.json`.
 * `lemmaId`/`formRole` group inflected forms into one WordCard, matching
 * how the real Clavier Métalo results page works.
 */
export const sampleWords: WordEntry[] = [
  { word: 'chat', phonemes: ['ch', 'a'], frequency: 100, level: 1, category: 'nom', lemmaId: 'chat', formRole: 'singulier' },
  { word: 'chats', phonemes: ['ch', 'a'], frequency: 40, level: 1, category: 'nom', lemmaId: 'chat', formRole: 'pluriel' },
  { word: 'chien', phonemes: ['ch', 'i', 'in'], frequency: 95, level: 1, category: 'nom', lemmaId: 'chien', formRole: 'simple' },
  { word: 'papa', phonemes: ['p', 'a', 'p', 'a'], frequency: 90, level: 1, category: 'nom', lemmaId: 'papa', formRole: 'simple' },
  { word: 'maman', phonemes: ['m', 'a', 'm', 'an'], frequency: 90, level: 1, category: 'nom', lemmaId: 'maman', formRole: 'simple' },
  { word: 'moto', phonemes: ['m', 'o', 't', 'o'], frequency: 60, level: 1, category: 'nom', lemmaId: 'moto', formRole: 'simple' },
  { word: 'vélo', phonemes: ['v', 'e', 'l', 'o'], frequency: 65, level: 1, category: 'nom', lemmaId: 'velo', formRole: 'simple' },
  { word: 'école', phonemes: ['e', 'c', 'o', 'l'], frequency: 85, level: 1, category: 'nom', lemmaId: 'ecole', formRole: 'simple' },
  { word: 'ballon', phonemes: ['b', 'a', 'l', 'on'], frequency: 70, level: 1, category: 'nom', lemmaId: 'ballon', formRole: 'singulier' },
  { word: 'ballons', phonemes: ['b', 'a', 'l', 'on'], frequency: 30, level: 1, category: 'nom', lemmaId: 'ballon', formRole: 'pluriel' },
  { word: 'bateau', phonemes: ['b', 'a', 't', 'o'], frequency: 55, level: 1, category: 'nom', lemmaId: 'bateau', formRole: 'simple' },
  { word: 'oiseau', phonemes: ['oi', 'z', 'o'], frequency: 50, level: 1, category: 'nom', lemmaId: 'oiseau', formRole: 'simple' },
  { word: 'souris', phonemes: ['s', 'ou', 'r', 'i'], frequency: 45, level: 1, category: 'nom', lemmaId: 'souris', formRole: 'simple' },
  { word: 'tortue', phonemes: ['t', 'o', 'r', 't', 'u'], frequency: 40, level: 1, category: 'nom', lemmaId: 'tortue', formRole: 'simple' },
  { word: 'lion', phonemes: ['l', 'i', 'on'], frequency: 50, level: 1, category: 'nom', lemmaId: 'lion', formRole: 'singulier' },
  { word: 'lions', phonemes: ['l', 'i', 'on'], frequency: 20, level: 1, category: 'nom', lemmaId: 'lion', formRole: 'pluriel' },
  { word: 'poisson', phonemes: ['p', 'oi', 's', 'on'], frequency: 55, level: 1, category: 'nom', lemmaId: 'poisson', formRole: 'singulier' },
  { word: 'poissons', phonemes: ['p', 'oi', 's', 'on'], frequency: 25, level: 1, category: 'nom', lemmaId: 'poisson', formRole: 'pluriel' },
  { word: 'table', phonemes: ['t', 'a', 'b', 'l'], frequency: 60, level: 1, category: 'nom', lemmaId: 'table', formRole: 'simple' },
  { word: 'robot', phonemes: ['r', 'o', 'b', 'o'], frequency: 45, level: 1, category: 'nom', lemmaId: 'robot', formRole: 'simple' },
  { word: 'fille', phonemes: ['f', 'ill'], frequency: 65, level: 1, category: 'nom', lemmaId: 'fille', formRole: 'simple' },
  { word: 'maison', phonemes: ['m', 'e2', 'z', 'on'], frequency: 75, level: 1, category: 'nom', lemmaId: 'maison', formRole: 'singulier' },
  { word: 'maisons', phonemes: ['m', 'e2', 'z', 'on'], frequency: 25, level: 1, category: 'nom', lemmaId: 'maison', formRole: 'pluriel' },
  { word: 'gâteau', phonemes: ['g', 'a', 't', 'o'], frequency: 55, level: 1, category: 'nom', lemmaId: 'gateau', formRole: 'simple' },
  { word: 'soleil', phonemes: ['s', 'o', 'l', 'ill'], frequency: 50, level: 1, category: 'nom', lemmaId: 'soleil', formRole: 'simple' },
  { word: 'lapin', phonemes: ['l', 'a', 'p', 'in'], frequency: 50, level: 1, category: 'nom', lemmaId: 'lapin', formRole: 'simple' },
  { word: 'nid', phonemes: ['n', 'i'], frequency: 20, level: 1, category: 'nom', lemmaId: 'nid', formRole: 'simple' },
  { word: 'domino', phonemes: ['d', 'o', 'm', 'i', 'n', 'o'], frequency: 15, level: 1, category: 'nom', lemmaId: 'domino', formRole: 'simple' },
  { word: 'fleur', phonemes: ['f', 'l', 'eu', 'r'], frequency: 40, level: 1, category: 'nom', lemmaId: 'fleur', formRole: 'singulier' },
  { word: 'fleurs', phonemes: ['f', 'l', 'eu', 'r'], frequency: 20, level: 1, category: 'nom', lemmaId: 'fleur', formRole: 'pluriel' },
  { word: 'montagne', phonemes: ['m', 'on', 't', 'a', 'gn'], frequency: 30, level: 1, category: 'nom', lemmaId: 'montagne', formRole: 'simple' },
  { word: 'petit', phonemes: ['p', 'eu', 't', 'i'], frequency: 60, level: 1, category: 'adjectif', lemmaId: 'petit', formRole: 'masculin' },
  { word: 'petite', phonemes: ['p', 'eu', 't', 'i', 't'], frequency: 55, level: 1, category: 'adjectif', lemmaId: 'petit', formRole: 'féminin' },
  { word: 'joli', phonemes: ['j', 'o', 'l', 'i'], frequency: 45, level: 1, category: 'adjectif', lemmaId: 'joli', formRole: 'masculin' },
  { word: 'jolie', phonemes: ['j', 'o', 'l', 'i'], frequency: 40, level: 1, category: 'adjectif', lemmaId: 'joli', formRole: 'féminin' },
  { word: 'manger', phonemes: ['m', 'an', 'j', 'e'], frequency: 50, level: 1, category: 'verbe', lemmaId: 'manger', formRole: 'infinitif' },
  { word: 'mangé', phonemes: ['m', 'an', 'j', 'e'], frequency: 45, level: 1, category: 'verbe', lemmaId: 'manger', formRole: 'participe_passé' },
  { word: 'mange', phonemes: ['m', 'an', 'j'], frequency: 48, level: 1, category: 'verbe', lemmaId: 'manger', formRole: 'il_elle_on' },
  { word: 'mangent', phonemes: ['m', 'an', 'j'], frequency: 30, level: 1, category: 'verbe', lemmaId: 'manger', formRole: 'ils_elles' },
  { word: 'sauter', phonemes: ['s', 'o', 't', 'e'], frequency: 35, level: 1, category: 'verbe', lemmaId: 'sauter', formRole: 'infinitif' },
  { word: 'sauté', phonemes: ['s', 'o', 't', 'e'], frequency: 30, level: 1, category: 'verbe', lemmaId: 'sauter', formRole: 'participe_passé' },
  { word: 'saute', phonemes: ['s', 'o', 't'], frequency: 32, level: 1, category: 'verbe', lemmaId: 'sauter', formRole: 'il_elle_on' },
  { word: 'sautent', phonemes: ['s', 'o', 't'], frequency: 18, level: 1, category: 'verbe', lemmaId: 'sauter', formRole: 'ils_elles' },
  { word: 'avec', phonemes: ['a', 'v', 'e2', 'c'], frequency: 65, level: 1, category: 'invariable', lemmaId: 'avec', formRole: 'simple' },
  { word: 'vite', phonemes: ['v', 'i', 't'], frequency: 55, level: 1, category: 'adverbe', lemmaId: 'vite', formRole: 'simple' },
  { word: 'wifi', phonemes: ['w', 'i', 'f', 'i'], frequency: 30, level: 1, category: 'nom', lemmaId: 'wifi', formRole: 'simple' },
  { word: 'taxi', phonemes: ['t', 'a', 'x', 'i'], frequency: 35, level: 1, category: 'nom', lemmaId: 'taxi', formRole: 'simple' },
  { word: 'huit', phonemes: ['ui', 't'], frequency: 40, level: 1, category: 'invariable', lemmaId: 'huit', formRole: 'simple' },
  { word: 'poing', phonemes: ['p', 'oin'], frequency: 20, level: 1, category: 'nom', lemmaId: 'poing', formRole: 'simple' },
]
